//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RegisterTable
    {
        [Key]
        public int RegiserId { get; set; }
      
        public string FirstName { get; set; }
      
        public string LastName { get; set; }
       
        public string Gender { get; set; }
       
        public string Phone { get; set; }
      
        public string Country { get; set; }
      
        public string State { get; set; }
      
        public string City { get; set; }
       
        public string Address { get; set; }
    }
}
